version: "3.4"
services:

  chat-api:
    container_name: chat-api
    environment:
      ConnectionStrings__ChatContext: "Data Source=sql-server-database; Initial Catalog=ChatDb; User Id=sa; Password=1StrongPassword*"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PATH=ChatApi
    depends_on:
      - sql-server-database
      - migrations
    command: "dotnet ChatApi.dll"
    ports:
      - "80:80"

  bot-api:
    container_name: bot-api
    environment:
      ConnectionStrings__ChatContext: "Data Source=sql-server-database; Initial Catalog=ChatDb; User Id=sa; Password=1StrongPassword*"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PATH=BotApi
    depends_on:
      - sql-server-database
      - rabbit
    command: "dotnet BotApi.dll"
    ports:
      - "70:80"

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    working_dir: /app
    environment:
      PATH: "$PATH:$HOME/.dotnet/tools/"
      PROJECT: "/app/ChatApi.csproj"
      MIGRATIONS_NAME: "InitialCreate"
      SQL_CONTEXT_CLASS: "ChatContext"
      ConnectionStrings__ChatContext: "Data Source=sql-server-database; Initial Catalog=ChatDb; User Id=sa; Password=1StrongPassword*"
    command: "bash ./Scripts/add-and-apply-migrations.sh"
    depends_on:
      - sql-server-database

  rabbit:
    image: rabbitmq:3.5
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=my_vhost

  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1StrongPassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - ConnectionStrings__ChatContext=Data Source=sql-server-database; Initial Catalog=ChatDb; User Id=sa; Password=1StrongPassword*
    volumes:
      - ../test:/test
      - ../src:/src
    working_dir: /src/ChatApi
    depends_on:
      - sql-server-database
      - migrations
    command:
      [
        "./Scripts/wait-for-it.sh",
        "sql-server-database:1433",
        "-t",
        "10",
        "--",
        "./Scripts/wait-for-it.sh",
        "migrations:5000",
        "-t",
        "10",
        "--",
        "dotnet",
        "test"
      ]